### ISSUE TITLE
uncompress without header

### ISSUE THREAD

**Issue by broganross** [rsgalloway/pyseq#19]
I ran into any interesting case today, file names without a header, formatting the Sequence, and then trying to uncompress it.
 
```
seq = pyseq.Sequence(["0001.tif", "0002.tif", "0003.tif"])
seq_str = seq.format("%h[%R]%t")
print pyseq.uncompress(seq_str, "%h[%R]%t")
```
Returns None.
However, this works:
```
seq = pyseq.Sequence(["0001.tif", "0002.tif", "0003.tif"])
seq_str = seq.format("%h%R%t")
print pyseq.uncompress(seq_str, "%h%R%t")
```

In the first case the regex for %h has escaped the [ and it's expecting there to be something before it.  In the second case it matches the '0001-000' as the header.  I worked around this by changing uncompress to use the whole path to match the regex.

I'm not quite sure the best approach for this.  Changing uncompress to parse the whole path seems like it might be a viable option, but it doesn't seems to break the idea that a sequence is contained inside a folder.
Changing the regex to be '\S*', would work but I don't think it's the right solution.
There's also the possibility of adding optionals to the format string: %h\?%R%t would convert the %h regex into (\S+)?.  So if a character that would usually be escaped has already been escaped consider it a regex character?  I don't know, just spit balling.

**Comment by rsgalloway** [comment]
Thanks for the report. It's worse than that, actually. If you inspect the results from `uncompress` when using the `%R` directive you can see if didn't uncompress the sequence correctly:

```python
>>> s = pyseq.uncompress(seq_str, "%h%R%t")
>>> len(s)
1
```

So it seems some of the regex in uncompress needs some love, at least the %`h` and `%R` directives. I'm also thinking maybe we should just add the square brackets to the `%R` formatting to make it clear that it's a list and not a range, e.g.

```python
>>> seq = pyseq.Sequence(["0001.tif", "0002.tif", "0003.tif"])
>>> print seq.format("%h%R%t")
[1-3].tif
```
It will also make it easier to distinguish `%r` from `%R` in uncompress. What do you think? i'm creating a branch for this issue.

**Comment by rsgalloway** [comment]
Potential fix for this issue in b9589cb855651c96aab249e53d9f328d0facb5d9
```python
>>> seq = pyseq.Sequence(["0001.tif", "0002.tif", "0003.tif"])
>>> seq_str = seq.format("%h%R%t")
>>> print seq_str
[1-3].tif
>>> seq2 = pyseq.uncompress(seq_str, "%h%R%t")
>>> len(seq2)
3
>>> print seq2.format("%h%r%t %R")
1-3.tif [1-3]
```
This update adds bracketing to the `%R` formatter, so I removed it from your example, but it should work either way.

**Comment by broganross** [comment]
Looks good to me, except for one thing.  The regex for %R has the comma baked in, instead of using 'range_join'
```
>>> import os
>>> os.environ["PYSEQ_RANGE_SEP"] = ".."
>>> import pyseq
>>> seq = pyseq.Sequence(["0001.tif", "0002.tif", "0004.tif"])
>>> s = seq.format("%h%R%t")
>>> print s
[1-2..4].tif
>>> print pyseq.uncompress(s, "%h%R%t")
None
```

If you change the regex to be:
```
 'R': '\[[\d\s?\-%s?]+\]' % re.escape(range_join),
```
It seems to work.

**Comment by rsgalloway** [comment]
Good catch. OK, great, closing this issue and will merge to master.
