### ISSUE TITLE
Sequence.head() returns invalid String

### ISSUE THREAD

**Issue by KengoSawa2** [rsgalloway/pyseq#22]
Hi Mr Ryan,
Thank you for the wonderful library :)

I think that this is a bug.

>seq = pyseq.Sequence(['Rainbow_bridge_2k_01_000001.dpx'])
>print(seq.head())
>Rainbow_bridge_2k_01_000001.dpx

I expect 'Rainbow_bridge_2k_01_'.
but return full filename.
And try to tail (), it was empty.

If more than one item exists, No problem.
>seq = pyseq.Sequence(['Rainbow_bridge_2k_01_000001.dpx','Rainbow_bridge_2k_01_000002.dpx'])
>print(seq.head())
>Rainbow_bridge_2k_01_

Can you fix this problem?
I tried to read the implementation of the head () and tail (), but could not understand what why this happens:(

**Comment by rsgalloway** [comment]
Thanks for the kind words!

Currently, at least two items in the sequence are required in order for pyseq to determine the head, tail and frame number. If you add at least one more item to your example, it will work:

```
>>> seq = pyseq.Sequence(['Rainbow_bridge_2k_01_000001.dpx', 'Rainbow_bridge_2k_01_000002.dpx'])
>>> seq.head()
'Rainbow_bridge_2k_01_'
```

This is equally plausible:

```
>>> seq = pyseq.Sequence(['Rainbow_bridge_2k_01_000001.dpx', 'Rainbow_bridge_2k_02_000001.dpx'])
>>> seq.head()
'Rainbow_bridge_2k_'
```

Does that help?

**Comment by KengoSawa2** [comment]
Thank you for reply!
I understood your suggestion and pyseq spec.

However, I do not know the method of generating a "sequence file name" of your proposal.

From the file name of 'Rainbow_bridge_2k_01_000001.dpx', or how to generate a non-existent file 'Rainbow_bridge_2k_01_000002.dpx' will be present in pyseq library?
Or I can be processed well in regular expressions?

I am a novice of the python, I don't know yet pythonic idea.
I am sorry not be a question of the 'pyseq' library...


## problem backgrounds
I am making a tool to divide the discontinuity sequence files in one folder to sub folder(s).
### exec before
![before](https://cloud.githubusercontent.com/assets/14103893/15137677/40d22346-16c6-11e6-8cf0-e9ad75305d31.png)
### exec after
![after](https://cloud.githubusercontent.com/assets/14103893/15137681/44428cd2-16c6-11e6-8fd9-2922f2ca52e5.png)

This is my problem..
### my problem before
![myproblem_before](https://cloud.githubusercontent.com/assets/14103893/15137699/5d5ee080-16c6-11e6-9237-edbf03c4b3ff.png)

### my problem after
![myproblem_after](https://cloud.githubusercontent.com/assets/14103893/15137702/611fb032-16c6-11e6-8c26-18729278e713.png)

**Comment by rsgalloway** [comment]
I'm not exactly sure of your implementation, but I would suggest using the _get_sequences_ function and the _missing()_ method on the resulting sequence object. e.g.

```
>>> seqs = pyseq.get_sequences("dpx_seq_test")
>>> seqs[0].missing()
[2, 3, 6]
```

This will tell you which files/frames are missing from the sequences in that directory. If you can post more details about your implementation I may be able to help more.

**Comment by KengoSawa2** [comment]
Thank you for your kindness.
For now, I've solved my problem!
