### ISSUE TITLE
lss: do not color output when output is redirected

### ISSUE THREAD

**Issue by maximd** [rsgalloway/pyseq#32]
Hi!

This is a feature request: by default, `lss` colorizes its output. It is perfect for interactive use but when the output is redirected to a file the color codes are still present.

It would be really helpful is those color codes could be striped when output is redirected (= colorize only when tty). Or maybe provide a command line parameter to suppress color output?

Thank you for such a useful tool!

**Comment by rsgalloway** [comment]
Apologies for the late reply. Yeah, I can see the usefulness of that. If you need this soon, then submit a PR and I'll merge it. Otherwise, I'll try to get to it when I have time.
