### ISSUE TITLE
Uncompress not working for documented example

### ISSUE THREAD

**Issue by mattdw** [rsgalloway/pyseq#34]
The example in uncompress at <https://github.com/rsgalloway/pyseq/blob/master/pyseq.py#L824>

```python
>>> seq2 = uncompress('./tests/files/a.%03d.tga 1-3 10 12-14', fmt='%h%p%t %R')
```

…always gives me `None` rather than a sequence. The %R regex seems to be looking for surrounding literal `[` `]`, but I'm just not quite sure what the intent there is. I'd be happy to write a patch if you're able to point me in the right direction for a fix!

(This is my preferred format, and closest to Nuke's handling, so it would be great to get it working.)

Cheers,
Matt.

**Comment by nebukadhezer** [comment]
Hey,

The docstring seems old the syntax changed you can see that in the unittests:

`seq2 = uncompress(
            './tests/files/a.%03d.tga [1-3, 10, 12-14]',
            fmt='%h%p%t %R'
        )`
so the numbers ought to be in square brackets.
Cheers
Johannes

**Comment by rsgalloway** [comment]
Thanks, Johannes. Closing this out.
