### ISSUE TITLE
cannot use .size() or .format("%d") on seqs from .walk()

### ISSUE THREAD

**Issue by tomtatchell** [rsgalloway/pyseq#39]
When getting all the image sequences from a root folder using:

    root_folder = "/Volumes/HDD1/Work/Job/Shots/"
    seqs = pyseq.walk(root_folder)
    for s in seqs:
        for x in s[2]:
            print(x.size())

this prints: 
`FileNotFoundError: [Errno 2] No such file or directory: '/Users/bbmp03/PycharmProjects/img_seq_tools/TL_070_Ren__1_0000.exr'`

which shows it is not going to the actual directory of the files, instead its looking in the directory of the script.

Is this the correct behavior?

**Comment by rsgalloway** [comment]
This is fixed in the version in the repo, not yet up on pypi however. Will push a 0.5.1 version soon.
