### ISSUE TITLE
Error encoding special character in a filename when performing pyseq.walk()

### ISSUE THREAD

**Issue by herronelou** [rsgalloway/pyseq#45]
Hi,
I have built a QT filebrowser that uses pyseq instead of the default walk functions, in order to show only one entry for filesequences.

Everything worked just fine, until someone dropped a file with a special character in there (™).
Quick fix is to rename the file, however it might happen again in the future, so I thought I'd report it.

```
File "/python/2.7/pyseq.py", line 1189, in walk
    yield root, dirs, get_sequences(files)
  File "/python/2.7/pyseq.py", line 1047, in get_sequences
    items = sorted(source, key=lambda x: str(x))
  File "/python/2.7/pyseq.py", line 1047, in <lambda>
    items = sorted(source, key=lambda x: str(x))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 45: ordinal not in range(128)
```

**Comment by herronelou** [comment]
I have tried with the latest version that was in the master branch as of the day I posted. (Not the version we use in production, but I tried using the latest when I ran into the bug). (Can't recall the version, and not at the office now)

FYI we're on python 2.7, I think Python 3 most likely handles this more elegantly.

**Comment by rsgalloway** [comment]
I still can't reproduce this with python 2.6, or 2.7 on the command line.

```
>>> for x in sorted(source, key=lambda x: str(x)): print x
...
test™.1.jpg
test™.2.jpg
```

Are you passing QStrings to pyseq?  We could try changing the encoding to utf-8

`
sorted(source, key=lambda x: unicode(x, "utf-8"))
`

**Comment by herronelou** [comment]
I will try to investigate it further soon. Thanks for looking into it.

**Comment by rsgalloway** [comment]
OK sure, let me know if you find out anything. If there's a bug, I'd like to squash it.

**Comment by herronelou** [comment]
So I did a very simple test:
`print str(u'™')`

That already fails.

Not sure how your test above succeeded, for me:
```
source = [u'test™.1.jpg', u'test™.2.jpg']
for x in sorted(source, key=lambda x: str(x)): print x
```
fails too.
`for x in sorted(source, key=lambda x: unicode(x)): print x` does work, though I tried replacing that in the pyseq code, but then I get issues at line 1000, in get_sequences:
    item = Item(items.pop(0))

I managed to get it eventually working (just the walk), but that involved making the class Item a child of unicode instead of str, and replacing a few things in the Item class. I may have broken other stuff so I'm not going to push that, but this is where I'm at.

**Comment by herronelou** [comment]
Using:
```
Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
```

**Comment by herronelou** [comment]
I haven't tried, I'm not really setup with the full git repo, I just have
pyseq.py installed. I'll give it a try tomorrow if I get a few minutes.

**Comment by rsgalloway** [comment]
OK, let me know. I'll try some tests on my end as well.

**Comment by herronelou** [comment]
Hey Ryan,
A little bit of progress on my end. The pyseq walk only fails if I pass it the path as a unicode (which is what Qt returns for most of its objects).
If I force it back to a string before the walk, as long as I'm in the latest version, it will work fine. 

We are still at 0.4.3 in production, and it's failing for that one.

I'm having some other strange issues, like if I try the Sequence.format() with anything containing `%s` it's failing, but I can't reproduce out of my package, I'm not sure why that is.

Another successful thing I had was to use unicode.encode('utf-8') instead of str() in a few places, but I still don't have a great implementation.

I can replace line 1170 by:
```
    source = os.path.abspath(source).encode('utf-8')
```
Which still passes the unittest, but if I add files in the file list for the unittest containing the special character, I get an assertionError, even though the strings seem similar:

```
AssertionError: '  10 012_vb_110_v001.%04d.png [1-10]\n  10 012_vb_110_v002.%04d.png [1-10]\n   7 a.%03d.tga [1-3, 10, 12-14]\n   1 alpha.txt\n   5 bnc01_TinkSO_tx_0_ty_0.%04d.tif [101-105]\n   5 bnc01_TinkSO_tx_0_ty_1.%04d.tif [101-105]\n   5 bnc01_TinkSO_tx_1_ty_0.%04d.tif [101-105]\n   5 bnc01_TinkSO_tx_1_ty_1.%04d.tif [101-105]\n   2 file.%02d.tif [1-2]\n   1 file.info.03.rgb\n   3 file01.%03d.j2k [1-2, 4]\n   4 file01_%04d.rgb [40-43]\n   4 file02_%04d.rgb [44-47]\n   4 file%d.03.rgb [1-4]\n   3 fileA.%04d.jpg [1-3]\n   3 fileA.%04d.png [1-3]\n   1 file_02.tif\n   2 test\xe2\x84\xa2.%d.jpg [1-2]\n   4 z1_001_v1.%d.png [1-4]\n   4 z1_002_v1.%d.png [1-4]\n   4 z1_002_v2.%d.png [1-4]\n' != '  10 012_vb_110_v001.%04d.png [1-10]\n  10 012_vb_110_v002.%04d.png [1-10]\n   7 a.%03d.tga [1-3, 10, 12-14]\n   1 alpha.txt \n   5 bnc01_TinkSO_tx_0_ty_0.%04d.tif [101-105]\n   5 bnc01_TinkSO_tx_0_ty_1.%04d.tif [101-105]\n   5 bnc01_TinkSO_tx_1_ty_0.%04d.tif [101-105]\n   5 bnc01_TinkSO_tx_1_ty_1.%04d.tif [101-105]\n   2 file.%02d.tif [1-2]\n   1 file.info.03.rgb \n   3 file01.%03d.j2k [1-2, 4]\n   4 file01_%04d.rgb [40-43]\n   4 file02_%04d.rgb [44-47]\n   4 file%d.03.rgb [1-4]\n   3 fileA.%04d.jpg [1-3]\n   3 fileA.%04d.png [1-3]\n   1 file_02.tif \n   2 test\xe2\x84\xa2.%d.jpg [1-2]\n   4 z1_001_v1.%d.png [1-4]\n   4 z1_002_v1.%d.png [1-4]\n   4 z1_002_v2.%d.png [1-4]\n'

```

**Comment by herronelou** [comment]
We are updating to latest, I've put a merge request, we're just in the middle of a massive pipeline/systems transition so we have to be careful with which packages we change.
I've made a fix on my code so that the path I give to pyseq passes a string rather than unicode, and while that still fails on the old version, it works fine in the new one.
