### ISSUE TITLE
pyseq.walk() execute on Python3, Consume huge memory and CPU.

### ISSUE THREAD

**Issue by KengoSawa2** [rsgalloway/pyseq#51]
Hi,
Thank you for great library:)

I found a behavior like a bug that occurred between pyseq 0.5.0 and the latest.
This problem occurs in Python 3.4.4 and Python 3.5.1, but it does not occur in Python 2.7.

Reproduction code and data are here:
https://drive.google.com/open?id=1xPG4x4Uv7RU-nI_IUGL-fO_I4CEyXplb

When executed, it consumes a large amount of memory at the following places.
https://github.com/rsgalloway/pyseq/blob/master/pyseq.py#L635
(and 1 cpu core busy occured)

The program can continue even after the problem has occurred.
However, since memory busy and CPU busy continue, it is impossible to continue the program.

This problem does not occur in pyseq 0.5.0 released on PyPI.
Therefore, I think there is regression bug in the fix from 0.5.0 to the latest pyseq.

My environment:
macOS 10.11.6
Python 3.4.4
Pyseq:latest (2018/11/28)

Regards

**Comment by broganross** [comment]
I was unable to recreate the issue under the following conditions:
OSX 10.13.6
Python 3.7.0
Latest Master commit a43d16de072dd9d93c2347ed15ed16c3cea23c7b which is from 2017/11/28 not 2018.

**Comment by KengoSawa2** [comment]
Thank you validation:)

This problem is not a matter of pyseq's code, it may be a problem of my environment.
I will report again on this issue.
There is a possibility of a problem of a lower layer library such as C library used by CPython.

**Comment by rsgalloway** [comment]
Thank you, Brogan, for testing this. Kengo, If you continue to experience this issue, others may be experiencing it also under similar environments so we'd like to know what you find out. In the meantime, I'll close this ticket.
