### ISSUE TITLE
Issues with strict padding

### ISSUE THREAD

**Issue by herronelou** [rsgalloway/pyseq#60]
Hi. 
I posted a couple of hours ago about an issue I was having with strict padding into the closed issue #41.

I tried to handle my issue by turning strict padding off, as it is more likely (at least in my case) that I would run into a sequence without padding( ```1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...```) than I am to run into multiple files with the same frame number but different padding (```file.1.jpg, file.01.jpg```).

It seemed at first to solve the issue, however this caused some issues with padding and sorting:
```pyhton
import pyseq
pyseq.strict_pad = False
sequence = pyseq.get_sequences(['file.7.jpg', 'file.8.jpg', 'file.9.jpg', 'file.10.jpg', 'file.11.jpg', 'file.12.jpg'])[0]
print sequence[0]
# Prints: file.10.jpg
print sequence._get_padding()
# Prints: %02d
```

Now I can't really tell if the Sequence object is meant to be sorted, as it has an append and insert method, I guess it's not meant to be sorted, however _get_padding() uses Item 0 to define the padding. That works if every item has the same padding (as in strict padding), but breaks in this case where there is no strict padding.

It sort of brings back what I was asking in #41 , if it might make sense to add a padding property to the sequence, as well as tracking if it's an inferred or explicit padding (being the smallest number if no item has a 0 padding, becomes explicit once an item with padding is added).

I will do a test implementation to see if it still passes unittests and see if it solves my issues in production.

**Comment by herronelou** [comment]
Did a possible implementation of that.
It's probably not perfect, but would be curious to hear feedback on it. See merge request #61

**Comment by herronelou** [comment]
In hindsight, this was probably overcomplicated. It would be nice though if pyseq understood non-padded sequences as in the example above.

**Comment by rsgalloway** [comment]
I can reproduce this issue, thanks for reporting it and apologies for the delay. Also, thanks for taking a stab at a fix ;)

It escaped detection originally because the non-padded example tests/files/z1_002_v1.%d.png only includes 4 single digit frame numbers :/ 

I have a branch with a potential fix here with a unit test, please test it and let me know if it addresses the issue for you:

https://github.com/rsgalloway/pyseq/tree/issue-60

I've also added a -s option to lss for convenience:

```
$ for i in {1..12}; do touch test.$i.exr; done
$ lss
   9 test.%d.exr [1-9]
   3 test.%02d.exr [10-12]
$ lss -s
  12 test.%d.exr [1-12]
```

**Comment by herronelou** [comment]
Hello.
It still seems like the sorting is broken, it works with your test because the sequence starts at 1 (and it happens to sort before 10, 11 and 12. If you start the sequence at 2, the sorting will be different and the get_padding function will return 2 again.

```
>>> sequence = pyseq.get_sequences(['file.7.jpg', 'file.8.jpg', 'file.9.jpg', 'file.10.jpg', 'file.11.jpg', 'file.12.jpg', 'file.87.jpg'])[0]
>>> for frame in sequence:
...     print frame
... 
file.10.jpg
file.11.jpg
file.12.jpg
file.7.jpg
file.8.jpg
file.87.jpg
file.9.jpg
```

interestingly, the default `sorted` function will sort them properly.

```
>>> for frame in sorted(sequence):  # also works with sequence.sort()
...     print frame
... 
file.7.jpg
file.8.jpg
file.9.jpg
file.10.jpg
file.11.jpg
file.12.jpg
file.87.jpg
```

**Comment by herronelou** [comment]
It also looks like like maybe you didn't push the code? The branch you linked is the same as master and is a few months old.

**Comment by rsgalloway** [comment]
Ah, sorry about that. Should be there now.

**Comment by rsgalloway** [comment]
The fix in that branch may be too simple.. did some more testing and it only works if one of the frames is a single digit. I'll dig deeper.

**Comment by herronelou** [comment]
Are sequences meant to be sorted? The only sorting I'm seeing is in the
get_sequences method, so maybe not. Sorting and then getting the padding
from the first element does produce more consistent results, although it's
impossible to tell for a sequence that contains 999 and 1000 if it was %03d
or %02d or %d

**Comment by rsgalloway** [comment]
I pushed another update to the [issue-60](https://github.com/rsgalloway/pyseq/tree/issue-60) branch that hopefully addresses this issue. Give it another test and let me know. I'd like to do a review and merge to master.

There's no sorting during the sequence building process (yet) for performance. Sorting could slow things down and performance is key when you're dealing with 1000s of files. You can always sort the sequence at the end. May look into ordered lists at some point.

**Comment by rsgalloway** [comment]
I'm wondering if strict padding should be disabled by default in lss since this issue will be manifest in cases where files have no pad. 

```
$ for i in {1..1200}; do touch test.$i.exr; done
$ lss
   9 test.%d.exr [1-9]
  90 test.%d.exr [10-99]
 900 test.%d.exr [100-999]
 201 test.%d.exr [1000-1200]
```

with strict pad disabled:

```
$ lss -s
1200 test.%d.exr [1-1200]
```

and it works with padded frames too:

```
$ for i in $(seq -f "%05g" 1 1200); do touch test.$i.exr; done
$ lss -s
1200 test.%05d.exr [1-1200]
```

**Comment by herronelou** [comment]
I was thinking strict padding should still allow sequences with no padding,
but nearly same outcome.

**Comment by rsgalloway** [comment]
I'm not sure that makes sense. By definition strict padding requires the pad lengths to match, literally the number of chars in the frame string must be equal. Otherwise, there's no way to tell for example if test.10000.exr is in the same seq as test.00001.exr. They might be, but if test.9999.exr also exists then you will get different results with and without strict padding.

**Comment by herronelou** [comment]
You're right. I guess it's more about allowing mixed padding within the
same sequence or not. I've had very few cases (2 to be exact) where I've
received badly formatted sequences where a few frames weren't padded
properly.
I've had a lot more cases where I have received non-padded sequences, or
sequences where the numbers passed the padding (example 2 padded sequences
reaching the 100s).
I ended up turning strict padding off because I never really needed it on,
as I've not yet encountered a folder containing 2 sequences with the same
name but different padding. I can see it could happen, but so far I haven't
seen it.

**Comment by rsgalloway** [comment]
I've posted a potential fix here: https://github.com/rsgalloway/pyseq/pull/63

cc: @broganross @nebukadhezer

**Comment by nebukadhezer** [comment]
Need to test here, but as we are mostly running with strict padding anyway, this should not pose a problem... 
Thanks for giving the headsup.

**Comment by broganross** [comment]
Nothing pops out to me as problematic in your PR.  We're running with strict_pad through the interface so there shouldn't be any issues.
I would also add that get_sequences (and iget_sequences) do sort, but since it's a standard string sort, instead of a natural sort, what they are seeing is expected.

**Comment by rsgalloway** [comment]
OK, thanks. Unless there are any concerns I'm going to merge #63 later today.

**Comment by rsgalloway** [comment]
this has been tagged and released
