### ISSUE TITLE
lss vs pyseq : multiple sequences

### ISSUE THREAD

**Issue by nyue** [rsgalloway/pyseq#62]
Hi,

  In the example showing lss, it is able to list two or more different sequences within the same directory.

  When I pass in the same files via the pyseq Sequence, it only returns one sequence

  Is there some way for Sequence to return multiple sequences ?

Cheers

**Comment by rsgalloway** [comment]
Hey Nicholas!

Thanks for the question, yes. Using the tests/files directory as an example:

>>> pyseq.get_sequences('tests/files')
[<pyseq.Sequence "012_vb_110_v001.1-10.png">, ... , <pyseq.Sequence
"z1_002_v2.1-4.png">]

$ pydoc pyseq.get_sequences
Help on function get_sequences in pyseq:

pyseq.get_sequences = get_sequences(source)
    Returns a list of Sequence objects given a directory or list that
contain
    sequential members.
   ...

Hope that helps.

Ryan
