### ISSUE TITLE
Link in side bar is broken

### ISSUE THREAD

**Issue by beatreichenbach** [rsgalloway/pyseq#72]

**Comment by rsgalloway** [comment]
hi @beatreichenbach can you provide a little more detail?

**Comment by rsgalloway** [comment]
I've updated the link to the one that works for now. Will look into why the GH link is not working. Closing this out for now (thanks again for the report).

**Comment by beatreichenbach** [comment]
> Will look into why the GH link is not working. Closing this out for now (thanks again for the report).
Because GitHub pages are on `.io` so you'd have to use:
[rsgalloway.github.io/pyseq/](http://rsgalloway.github.io/pyseq/)
