### ISSUE TITLE
Walk directory trees

### ISSUE THREAD

**Issue by rsgalloway** [rsgalloway/pyseq#8]
Ability to walk a directory and show all found sequences in a tree format.

**Comment by broganross** [comment]
Were you thinking only lss?  or in getSequences as well?
maybe an igetSequences, as a generator, for use in lss?

**Comment by rsgalloway** [comment]
Hmm, that's an interesting idea. Perhaps a pyseq.walk() function that yields Sequences? Similar to os.walk(). Seems intuitive to me.

I was thinking something akin to `tree`, I guess, but collapses the sequences. Maybe this should be a separate tool, like `trees` or .. ?

**Comment by broganross** [comment]
If you take a look at 6ebe2e5affd380f89189b4d844a515cdc856b57c I gave lss a walk option.
Really I switched to always walk, but if you don't give it the -w arg it only checks the top directory.
But, adding walk to getSequences would be a bit different.  I think maybe a pyseq.walk would be a good addition.

**Comment by rsgalloway** [comment]
What do you think about changing --walk to -r/--recursive and give it an optional value so that you can control the amount of recursion? e.g.
```
> lss -r tests/
tests            
├── files 
│   ├── 10 012_vb_110_v001.%04d.png 1-10
...snip...
│   └── 4 z1_002_v2.%d.png 1-4
└── test_pyseq.py

> lss -r 1 tests/
tests/
├── files
└── test_pyseq.py
```

**Comment by broganross** [comment]
-r would make more sense.  I actually started working on a pyseq.walk last night that yields root, dirs, and seqs.  And I was writing an stree script but it makes more sense to do lss -r and have the script call pyseq.walk or pyseq.getSequences as needed.
Getting that print out with the proper lines was tripping me up a bit.

**Comment by rsgalloway** [comment]
Agreed. Yeah, the formatting is a bit tricky. See if this helps at all .. there's also Newick format :)

https://github.com/alembic/alembic/blob/master/python/examples/cask/bin/abctree
